// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQYaYdpwSdQRqZHC7fM__1bWUAucWYkw',
    appId: '1:807465466309:web:9decfe4bf450ebbe4ff3ac',
    messagingSenderId: '807465466309',
    projectId: 'flash-chat-4f352',
    authDomain: 'flash-chat-4f352.firebaseapp.com',
    storageBucket: 'flash-chat-4f352.firebasestorage.app',
    measurementId: 'G-29F7C35RRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OZKBaf1rcHxaI8GT5fZ4PiXXovAnFP8',
    appId: '1:807465466309:android:4bbdedc19703cb6f4ff3ac',
    messagingSenderId: '807465466309',
    projectId: 'flash-chat-4f352',
    storageBucket: 'flash-chat-4f352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCov3RZy3TVpD9B0dU8bc_5ZNRa-L6dMoM',
    appId: '1:807465466309:ios:07dcb67c0e8df5d24ff3ac',
    messagingSenderId: '807465466309',
    projectId: 'flash-chat-4f352',
    storageBucket: 'flash-chat-4f352.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCov3RZy3TVpD9B0dU8bc_5ZNRa-L6dMoM',
    appId: '1:807465466309:ios:07dcb67c0e8df5d24ff3ac',
    messagingSenderId: '807465466309',
    projectId: 'flash-chat-4f352',
    storageBucket: 'flash-chat-4f352.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWQYaYdpwSdQRqZHC7fM__1bWUAucWYkw',
    appId: '1:807465466309:web:cf68e132f2046e5d4ff3ac',
    messagingSenderId: '807465466309',
    projectId: 'flash-chat-4f352',
    authDomain: 'flash-chat-4f352.firebaseapp.com',
    storageBucket: 'flash-chat-4f352.firebasestorage.app',
    measurementId: 'G-K66GVGDPR8',
  );
}
